swagger: "2.0"
info:
  description: ""
  version: "2.0.0"
  title: "JtlReporter Listener Service"
basePath: "/api/v2"
tags:
- name: "test-run"


schemes:
- "http"
paths:
  /test-run/log-samples:
    post:
      tags:
      - "samples"
      summary: "Add new samples"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LogSamples"
      responses:
        "400":
          description: "Invalid input"
      security:
      - jwtToken: []
  

   
securityDefinitions:
  jwtToken:
    type: "apiKey"
    name: "x-access-token"
    in: "header"
  
definitions:
  Sample:
    type: "object"
    required:
     - timeStamp
     - elapsed
     - label
     - responseCode
     - responseMessage
     - threadName
     - success
     - bytes
     - grpThreads
     - allThreads
     - latency
     - hostname
     - connect
    properties:
      timeStamp:
        type: "integer"
      elapsed:
        type: "integer"
      label:
        type: "string"
      responseCode:
        type: "integer"
      responseMessage:
        type: "string"
      threadName:
        type: "string"
      success:
        type: "boolean"
      bytes:
        type: "integer"
      sentBytes:
        type: "integer"
      grpThreads:
        type: "integer"
      allThreads:
        type: "integer"
      latency:
        type: "integer"
      hostname:
        type: "string"
      connect: 
        type: "integer"

  LogSamples:
    type: "object"
    required:
    - "itemId"
    - "samples"
    properties:
      itemId:
        type: "string"
        format: "uuid"
      samples:
        type: "array"
        maxItems: 500
        items:
          $ref: "#/definitions/Sample"

